definitions:
  dto.GetOtpRequest:
    properties:
      mobileNumber:
        maxLength: 11
        minLength: 11
        type: string
    required:
    - mobileNumber
    type: object
  dto.LoginByUsernameRequest:
    properties:
      password:
        minLength: 6
        type: string
      username:
        minLength: 5
        type: string
    required:
    - password
    - username
    type: object
  dto.OrderCreateDTO:
    properties:
      giftcard_id:
        type: integer
      quantity:
        type: integer
      status:
        enum:
        - pending
        - paid
        - failed
        - delivered
        type: string
      unit_price:
        type: number
      user_id:
        type: integer
    required:
    - giftcard_id
    - quantity
    - unit_price
    - user_id
    type: object
  dto.OrderDeleteDTO:
    properties:
      order_id:
        type: integer
    required:
    - order_id
    type: object
  dto.OrderGetByIDDTO:
    properties:
      order_id:
        type: integer
    required:
    - order_id
    type: object
  dto.OrderStatusUpdateDTO:
    properties:
      order_id:
        type: integer
      status:
        enum:
        - pending
        - paid
        - failed
        - delivered
        type: string
    required:
    - order_id
    - status
    type: object
  dto.OrdersByUserDTO:
    properties:
      user_id:
        type: integer
    required:
    - user_id
    type: object
  dto.RegisterLoginByMobileRequest:
    properties:
      mobileNumber:
        maxLength: 11
        minLength: 11
        type: string
      otp:
        maxLength: 6
        minLength: 6
        type: string
    required:
    - mobileNumber
    - otp
    type: object
  dto.RegisterUserByUsernameRequest:
    properties:
      email:
        minLength: 6
        type: string
      firstName:
        minLength: 3
        type: string
      lastName:
        minLength: 6
        type: string
      password:
        minLength: 6
        type: string
      username:
        minLength: 5
        type: string
    required:
    - firstName
    - lastName
    - password
    - username
    type: object
  helper.BaseHttpResponse:
    properties:
      error: {}
      result: {}
      resultCode:
        $ref: '#/definitions/helper.ResultCode'
      success:
        type: boolean
      validationErrors:
        items:
          $ref: '#/definitions/validations.ValidationError'
        type: array
    type: object
  helper.ResultCode:
    enum:
    - 0
    - 40001
    - 40101
    - 40301
    - 40401
    - 42901
    - 42902
    - 50001
    - 50002
    type: integer
    x-enum-varnames:
    - Success
    - ValidationError
    - AuthError
    - ForbiddenError
    - NotFoundError
    - LimiterError
    - OtpLimiterError
    - CustomRecovery
    - InternalError
  validations.ValidationError:
    properties:
      message:
        type: string
      property:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/orders:
    post:
      consumes:
      - application/json
      description: ایجاد یک سفارش برای کاربر
      parameters:
      - description: OrderCreateRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.OrderCreateDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "400":
          description: Validation Failed
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "500":
          description: Failed
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
      security:
      - BearerAuth: []
      summary: ایجاد سفارش جدید
      tags:
      - Orders
  /v1/orders/by-user:
    post:
      consumes:
      - application/json
      description: دریافت لیست سفارشات یک کاربر
      parameters:
      - description: OrdersByUserRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.OrdersByUserDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "400":
          description: Validation Failed
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
      security:
      - BearerAuth: []
      summary: دریافت همه سفارشات کاربر
      tags:
      - Orders
  /v1/orders/delete:
    delete:
      consumes:
      - application/json
      description: حذف یک سفارش
      parameters:
      - description: DeleteOrderRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.OrderDeleteDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "400":
          description: Validation Failed
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "500":
          description: Failed
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
      security:
      - BearerAuth: []
      summary: حذف سفارش
      tags:
      - Orders
  /v1/orders/get:
    post:
      consumes:
      - application/json
      description: دریافت اطلاعات یک سفارش با شناسه
      parameters:
      - description: OrderGetRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.OrderGetByIDDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "400":
          description: Validation Failed
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
      security:
      - BearerAuth: []
      summary: دریافت سفارش
      tags:
      - Orders
  /v1/orders/update-status:
    put:
      consumes:
      - application/json
      description: تغییر وضعیت سفارش (pending, paid, delivered, failed)
      parameters:
      - description: UpdateOrderStatusRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.OrderStatusUpdateDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "400":
          description: Validation Failed
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "500":
          description: Failed
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
      security:
      - BearerAuth: []
      summary: بروزرسانی وضعیت سفارش
      tags:
      - Orders
  /v1/users/login-by-mobile:
    post:
      consumes:
      - application/json
      description: RegisterLoginByMobileNumber
      parameters:
      - description: RegisterLoginByMobileRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterLoginByMobileRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
      summary: RegisterLoginByMobileNumber
      tags:
      - Users
  /v1/users/login-by-username:
    post:
      consumes:
      - application/json
      description: LoginByUsername
      parameters:
      - description: LoginByUsernameRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginByUsernameRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
      summary: LoginByUsername
      tags:
      - Users
  /v1/users/refresh-token:
    post:
      consumes:
      - application/json
      description: RefreshToken
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "401":
          description: Failed
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
      summary: RefreshToken
      tags:
      - Users
  /v1/users/register-by-username:
    post:
      consumes:
      - application/json
      description: RegisterByUsername
      parameters:
      - description: RegisterUserByUsernameRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterUserByUsernameRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
      summary: RegisterByUsername
      tags:
      - Users
  /v1/users/send-otp:
    post:
      consumes:
      - application/json
      description: Send otp to user
      parameters:
      - description: GetOtpRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.GetOtpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/helper.BaseHttpResponse'
      summary: Send otp to user
      tags:
      - Users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
